{{- if and .Values.rbac.enabled .Values.rbac.clusterRole.create -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ default (printf "%s-clusterrole" .Release.Name) .Values.rbac.clusterRole.name }}
  labels:
    {{- include "kepler.labels" . | nindent 4 }}
  {{- with .Values.rbac.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
{{- range .Values.rbac.clusterRole.rules }}
- apiGroups: 
    {{- toYaml .apiGroups | nindent 4 }}
  resources:
    {{- toYaml .resources | nindent 4 }}
  verbs:
    {{- toYaml .verbs | nindent 4 }}
{{- end }}

{{- end }}