{{- if .Values.namespace.name }}

{{- if and .Values.rbac.enabled .Values.rbac.role.create -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ default (printf "%s-role" .Release.Name) .Values.rbac.role.name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{- include "kepler.labels" . | nindent 4 }}
  {{- with .Values.rbac.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ .Release.Name }}-scc
  resources:
  - SecurityContextConstraints
  verbs:
  - use

{{- end }}

{{- end }}