{{- if .Values.namespace.name }}

{{- range .Values.secretsEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .name }}{{ .name }}{{ else }}{{ include "kepler.fullname" $ }}-secret{{ end }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/part-of: {{ include "kepler.fullname" $ }}
    app.kubernetes.io/managed-by: Helm
data:
{{- if kindIs "slice" .data }}
{{- range .data }}
  {{- if and (hasKey . "name") (hasKey . "path") }}
  {{ .name }}: |-
{{- $.Files.Get .path | nindent 4 | trimSuffix "\n" }}
  {{- end }}
{{- end }}
{{- else if kindIs "map" .data }}
{{- range $key, $value := .data }}
  {{ $key }}: "{{ $value | b64enc }}"
{{- end }}
{{- end }}
---
{{- end }}

{{- end }}