apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:

  labels:
    app: telemetry
    kafka-cluster: telemetry

  name: telemetry
  namespace: observability-kafka

spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      # auto.create.topics.enable: false
      # delete.topic.enable: false
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 2
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 2
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: external
        port: 9093
        tls: true
        type: route
    replicas: 3
    resources: {}
    storage:
      size: 50Gi
      type: persistent-claim
  zookeeper:
    replicas: 1
    resources: {}
    storage:
      size: 5Gi
      type: persistent-claim