{{- if .Values.namespace.name }}

{{- if and .Values.rbac.enabled .Values.rbac.serviceAccount.create -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-serviceaccount" .Release.Name) .Values.rbac.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kepler.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- end }}

{{- end }}