{{- range .Values.service }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | default (printf "%s-%s" (include "postgresql.fullname" $) (.serviceType | lower)) }}
  labels:
    {{- include "postgresql.labels" $ | nindent 4 }}
spec:
  type: {{ .serviceType }}
  ports:
    {{- range $.Values.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "postgresql.selectorLabels" $ | nindent 4 }}

---

{{- end }}
{{- end }}