{{- if .Values.serviceAccount.create -}}
apiVersion: v1

kind: ServiceAccount

metadata:
  name: {{ .Values.serviceAccount.name | default (printf "%s-sa" .Release.Name) }} 

  labels:
    {{- include "postgresql.labels" . | nindent 4 }}

  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}