apiVersion: v2
name: postgresql
description: A Helm chart for Kubernetes

version: 1.0.0

dependencies:
  - name: postgresql
    version: "1.0.0"
    repository: "file://charts/01-postgresql"
    condition: subcharts.postgresql
    tags:
      - postgresql