kind: Deployment
apiVersion: apps/v1
metadata:
  name: infra-telemetry-collector
  labels:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/name: infra-telemetry-collector
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/version: 0.107.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/part-of: opentelemetry
  template:
    metadata:
      labels:
        app.kubernetes.io/component: opentelemetry-collector
        app.kubernetes.io/name: infra-telemetry-collector
        app.kubernetes.io/part-of: opentelemetry
        app.kubernetes.io/version: 0.107.0
    spec:
      restartPolicy: Always
      containers:
        - name: otc-container
          resources: {}
            # limits:
            #   cpu: 550m
            #   memory: 8000Mi
            # requests:
            #   cpu: 500m
            #   memory: 770Mi
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: K8S_NODE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          ports:
            - name: metrics
              containerPort: 8888
              protocol: TCP
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: otc-internal
              mountPath: /conf
          image: 'ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.107.0'
          args:
            - '--config=/conf/collector.yaml'
            - '--feature-gates=-component.UseLocalHostAsDefaultHost'
      serviceAccount: infra-telemetry-collector
      volumes:
        - name: otc-internal
          configMap:
            name: infra-telemetry-collector
            items:
              - key: collector.yaml
                path: collector.yaml
            defaultMode: 420
