kind: ServiceAccount
apiVersion: v1
metadata:
  name: infra-telemetry-collector
  labels:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/name: infra-telemetry-collector
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/version: 0.107.0
secrets:
  - name: infra-telemetry-collector-dockercfg
imagePullSecrets:
  - name: infra-telemetry-collector-dockercfg
