apiVersion: v2
name: trino
description: A Helm chart for Trino

version: 1.0.0

dependencies:

  - name: coordinator
    version: "1.0.0"
    repository: "file://charts/coordinator"
    condition: subcharts.coordinator
    tags:
      - coordinator

  - name: worker
    version: "1.0.0"
    repository: "file://charts/worker"
    condition: subcharts.worker
    tags:
      - worker