apiVersion: v2
name: edge
description: A Helm chart for Kubernetes

version: 1.0.0

dependencies:

  - name: dashboard
    version: "1.0.0"
    repository: "file://charts/03-dashboard"
    condition: subcharts.dashboard
    tags:
      - dashboard