nameOverride: ""

subcharts:
  postgresql: true
  backend: true
  dashboard: true

#############################################################

postgresql:

  replicaCount: 1

  containerName: ""

  image:
    registry: quay.io
    username: zagaos
    name: zaga-postgres15-rhel9
    pullPolicy: IfNotPresent
    tag: latest
  languageFramework: postgresql
  

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  args: {}

  ports:
    - name: jdbc-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432


  service:
    - enabled: true
      serviceType: ClusterIP
      name: admin-db
    - enabled: true
      serviceType: LoadBalancer
      name: admin-db-lb


  configmapEnv:
    - name: ""
      data:
        DATABASES: userdb
        PASSWORDS: usermanager123$
        USERS: usermanager

  volumes: 
    - type: PersistentVolumeClaim
      apiVersion: v1
      accessModes: ReadWriteOnce
      volumeName: ""
      mountPath: /storage
      storageSize: "4Gi"

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  resources: {}

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  nodeSelector: {}

  tolerations: []

  affinity: {}

#############################################################

backend:

  replicaCount: 1

  containerName: ""

  image:
    registry: quay.io
    username: zagaos
    name: zagaobserve-admin-manager-api 
    pullPolicy: IfNotPresent
    tag: latest
    strategy: ""
  languageFramework: python
  

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  serviceAccount:
    create: false
    annotations: {}
    name: ""


  ports:
    - name: http
      subdomainName: admin-backend
      port: 8000
      protocol: TCP
      targetPort: 8000
      routePolicy:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect

  service:
    - enabled: true
      serviceType: ClusterIP
      name: admin-backend
    - enabled: false
      serviceType: LoadBalancer
      name: admin-backend-lb

  routes:
    enabled: true
    tls: true
    annotations: {}

  ingress:
    enabled: false
    className: ""
    tls: false
    annotations: {}

  secretsEnv: {}

  configmapEnv:
    - name: ""
      mount: ""
      mountPath: ""
      data:
        POSTGRES_USER: usermanager
        POSTGRES_PASSWORD: usermanager123$
        POSTGRES_HOST: admin-db.observability-edge.svc.cluster.local
        POSTGRES_PORT: '5432'
        POSTGRES_DB: userdb

  env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace  

  probes:
    readiness:
    liveness:

  volumes: {}

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

#############################################################

dashboard:

  replicaCount: 1

  containerName: ""

  image:
    registry: quay.io
    username: zagaos
    name: quay.io/zagaos/zagaobserve-admin-manager-dashboard 
    pullPolicy: IfNotPresent
    tag: latest
    strategy: ""
  languageFramework: react
  
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  serviceAccount:
    create: false
    annotations: {}
    name: ""


  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      subdomainName: admin-dashboard
      routePolicy:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect

  service:
    - enabled: true
      serviceType: ClusterIP
      name: admin-dashboard
    - enabled: false
      serviceType: LoadBalancer
      name: admin-dashboard-lb

  routes:
    enabled: true
    tls: true
    annotations: {}

  ingress:
    enabled: false
    className: ""
    tls: false
    annotations: {}
      # cert-manager.io/cluster-issuer: zagaadmin-cluster-issuer

  secretsEnv: {}

  configmapEnv: {}

  probes:
    readiness:
    liveness:

  volumes: {}

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}