replicaCount: 1

containerName: ""

image:
  registry: quay.io
  username: zagaos
  name: kafka-observ-testcase
  pullPolicy: IfNotPresent
  tag: new-topicconf
  strategy: ""

languageFramework: spring-boot

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
    instrumentation.opentelemetry.io/inject-java: 'true'

podSecurityContext: {}

securityContext: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""


ports:
  - name: http
    subdomainName: kafka-srv
    port: 8080
    protocol: TCP
    targetPort: 8080
    routePolicy:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

service:
  - enabled: true
    serviceType: ClusterIP
    name: kafka-srv
  - enabled: false
    serviceType: LoadBalancer
    name: kafka-srv-lb

routes:
  enabled: true
  tls: false
  annotations: {}

ingress:
  enabled: false
  className: ""
  tls: false
  annotations: {}

secretsEnv: {}

configmapEnv:
  - name: ""
    mount: ""
    mountPath: ""
    data:
      KAFKA_PRODUCE_TOPIC: kafkasrv 
      KAFKA_URL: telemetry-kafka-bootstrap.observability-kafka.svc.cluster.local:9092

env: {}
args: {}

probes:
  readiness:
  liveness:

volumes: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}