kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: kepler-exporter-scc
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kepler-exporter
    app.kubernetes.io/part-of: kepler
    sustainable-computing.io/app: kepler
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities: null
defaultAddCapabilities:
- SYS_ADMIN
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: true
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- kepler
- system:serviceaccount:kepler:kepler-exporter-sa
volumes:
- configMap
- emptyDir
- hostPath
- projected