kind: ServiceAccount
apiVersion: v1
metadata:
  name: kepler-exporter-sa
  namespace: kepler
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kepler-exporter
    app.kubernetes.io/part-of: kepler
    sustainable-computing.io/app: kepler