kind: ConfigMap
apiVersion: v1
metadata:
  name: kepler-exporter-cm
  namespace: kepler
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kepler-exporter
    app.kubernetes.io/part-of: kepler
    sustainable-computing.io/app: kepler
data:
  CGROUP_METRICS: '*'
  ENABLE_EBPF_CGROUPID: 'true'
  ENABLE_QAT: 'false'
  EXPOSE_HW_COUNTER_METRICS: 'true'
  KEPLER_LOG_LEVEL: '1'
  EXPOSE_IRQ_COUNTER_METRICS: 'true'
  ENABLE_GPU: 'true'
  BIND_ADDRESS: '0.0.0.0:9102'
  METRIC_PATH: /metrics
  REDFISH_SKIP_SSL_VERIFY: 'true'
  EXPOSE_KUBELET_METRICS: 'true'
  ENABLE_PROCESS_METRICS: 'false'
  MODEL_CONFIG: CONTAINER_COMPONENTS_ESTIMATOR=false
  REDFISH_PROBE_INTERVAL_IN_SECONDS: '60'
  EXPOSE_CGROUP_METRICS: 'true'
  CPU_ARCH_OVERRIDE: ''
  KEPLER_NAMESPACE: kepler