replicaCount: 1

containerName: ""

image:
  registry: ghcr.io/open-telemetry
  username: opentelemetry-collector-releases
  name: opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  tag: 0.107.0

namespace:
  name: "otel-collector"
  annotations:
    openshift.io/description: otel-collector
    openshift.io/display-name: ""
    openshift.io/sa.scc.mcs: s0:c11,c10
    openshift.io/sa.scc.supplemental-groups: 1000130000/10000
    openshift.io/sa.scc.uid-range: 1000130000/10000
  labels:
    kubernetes.io/metadata.name: otel-collector
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.24

rbac:
  enabled: true

  serviceAccount:
    create: true
    name: ""
    annotations: {}

  role:
    create: false
    name: ""
    annotations: {}

  clusterRole:
    create: true
    name: ""
    annotations: {}
    rules:
      - verbs:
          - get
        apiGroups:
          - ''
        resources:
          - nodes/stats
          - nodes/proxy
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - ''
        resources:
          - events
          - namespaces
          - namespaces/status
          - nodes
          - nodes/spec
          - pods
          - pods/status
          - replicationcontrollers
          - replicationcontrollers/status
          - resourcequotas
          - services
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - apps
        resources:
          - daemonsets
          - deployments
          - replicasets
          - statefulsets
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - extensions
        resources:
          - daemonsets
          - deployments
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - batch
        resources:
          - jobs
          - cronjobs
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - autoscaling
        resources:
          - horizontalpodautoscalers
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - quota.openshift.io
        resources:
          - clusterresourcequotas
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - config.openshift.io
        resources:
          - infrastructures
          - infrastructures/status
          - networks
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - operator.openshift.io
        resources:
          - networks
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - metrics.k8s.io
        resources:
          - nodes
          - pods
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - network.operator.openshift.io
        resources:
          - '*'
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - networking.k8s.io
        resources:
          - '*'

  roleBinding:
    create: false
    name: ""
    annotations: {}

  clusterRoleBinding:
    create: true
    name: ""
    annotations: {}

  scc:
    create: true
    name: ""
    annotations:
      kubernetes.io/description: 'privileged allows access to otel-collector'

imageUpdateStrategy: ""

hostPID: "true"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

containerSecurityContext:
  privileged: true

DownwardApiEnv:
  - name: K8S_NODE_IP
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.hostIP
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: spec.nodeName

env: {}

secretsEnv: {}

configmapEnv:
  - name: "otel-collector-cm"
    mount: true
    mountPath: /conf
    filePath: true
    data:
      - name: collector.yaml
        path: configs/otel-config.yaml 

volumes: {}

resources: {}
  # limits:
  #   cpu: 600m
  #   memory: 1128Mi
  # requests:
  #   cpu: 600m
  #   memory: 1128Mi

nodeSelector: {}

tolerations: []

affinity: {}

args:
  - '--config=/conf/collector.yaml'
  - '--feature-gates=-component.UseLocalHostAsDefaultHost'

command: {}

ports:
  - name: metrics
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318

service:
  - enabled: false
    serviceType: ClusterIP
    name: otel-collector
  - enabled: false
    serviceType: LoadBalancer
    name: otel-collector-lb

routes:
  enabled: false
  tls: false
  annotations: {}

ingress:
  enabled: false
  className: ""
  tls: false
  annotations: {}

probes:
  readiness: {}
  liveness:
    httpGet:
      path: /healthz
      port: 9102
      scheme: HTTP
    initialDelaySeconds: 10
    timeoutSeconds: 10
    periodSeconds: 60
    successThreshold: 1
    failureThreshold: 5
  startup: {}