kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infra-telemetry-cr
  labels:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/name: infra-telemetry-collector
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/version: 0.107.0
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - nodes/stats
      - nodes/proxy
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - quota.openshift.io
    resources:
      - clusterresourcequotas
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
      - infrastructures/status
      - networks
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - operator.openshift.io
    resources:
      - networks
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - network.operator.openshift.io
    resources:
      - '*'
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - '*'
